### ISSUE TITLE
Treating `ltr` as default result in unexpected style changes.

### ISSUE THREAD

**Issue by irfanhudda** [gasolin/postcss-bidirection#10]
As we discussed in #6 to treat `ltr` as default but looks like it can have unexpected problems.

## Description

Consider the CSS

```css
.element {
  position: absolute;
  offset-inline-start: 20px;
  background-color: red;
}
```

This is currently converted to 
```css
.element {
  position: absolute;
  left: 20px;
  background-color: red;
}

html[dir="rtl"] .element {
  right: 20px;
}

```

It can be easier to look at example here on jsfiddle [https://jsfiddle.net/6nvbxbvx/1/](https://jsfiddle.net/6nvbxbvx/1/)

While we are expecting something like this [https://jsfiddle.net/avsw1wn5/1/](https://jsfiddle.net/avsw1wn5/1/)

It might be better to convert the CSS to 
```css
.element {
  position: absolute;
  background-color: red;
}

html[dir="rtl"] .element {
  right: 20px;
}

html[div="ltr"] .element {
  left: 20px;
}
```

Let me know what you think.
