### ISSUE TITLE
Support multi-selector rules

### ISSUE THREAD

**Issue by jasonLaster** [gasolin/postcss-bidirection#5]
Bi-direction does not support multi-selector rules

### Use case
```css
.file svg,
.domain svg,
.folder svg,
.refresh svg,
.worker svg {
  margin-inline-end: 5px;
}
```

### expected output
```css
html[dir="ltr"] .file svg,
html[dir="ltr"] .domain svg,
html[dir="ltr"] .folder svg,
html[dir="ltr"] .refresh svg,
html[dir="ltr"] .worker svg {
  margin-right: 5px;
}

html[dir="rtl"] .file svg,
html[dir="rtl"] .domain svg,
html[dir="rtl"] .folder svg,
html[dir="rtl"] .refresh svg,
html[dir="rtl"] .worker svg {
  margin-left: 5px;
}
```

### actual output

```css
html[dir="ltr"] .file svg,
.domain svg,
.folder svg,
.refresh svg,
.worker svg {
  margin-right: 5px;
}

html[dir="rtl"] .file svg,
.domain svg,
.folder svg,
.refresh svg,
.worker svg {
  margin-left: 5px;
}
```

**note** please let me do this :) I'd enjoy hacking on bi-direction!
