### ISSUE TITLE
Specificity of selector is changed

### ISSUE THREAD

**Issue by irfanhudda** [gasolin/postcss-bidirection#6]
When we use this plugin it was found that it changes specificity of selectors which can have some unwanted side-effects. Here's an example from devtools-html/debugger.html#1867

## Desciption
We had two files one was `WelcomeBox.css`
```css
.welcomebox .toggle-button-end {
  bottom: 11px;
  position: absolute;
  top: auto;
}
```

And other was `PaneToggle.css`
```css
.toggle-button-end {
  top: 7px;
  offset-inline-end: 0;
}
```

After conversion the second snippet was converted to 
```css
html:not([dir="rtl"]) .toggle-button-end {
  top: 7px;
  right: 0;
}

html[dir="rtl"] .toggle-button-end {
  top: 7px;
  left: 0;
}
```

The problem here is that, now specificity of `html:not([dir="rtl"]) .toggle-button-end` and `html[dir="rtl"] .toggle-button-end` is greater than `.welcomebox .toggle-button-end` which lead to unexpected result in the referenced issue.

## Possible solution?
While it may not be possible to eliminate this problem completely, we might be able to limit the problem caused by using following procedure

```css
.toggle-button-end {
  top: 7px;
  offset-inline-end: 0;
}
```

Should be converted to 
```css
.toggle-button-end {
  top: 7px;
}

html:not([dir="rtl"]) .toggle-button-end {
  right: 0;
}

html[dir="rtl"] .toggle-button-end {
  left: 0;
}
```

This will make sure that only Bi-directional attributes will be affected when specificity changes.

**Comment by gasolin** [comment]
@irfanhudda good catch!

At the time there's no `offset-inline-end` syntax available, we use these syntax in Gaia (Firefox OS UI)

```css
.toggle-button-end {
  top: 7px;
  right: 0;
}

html[dir="rtl"] .toggle-button-end {
  left: 0;
}
```

Which treat `ltr` as default and only overwrite the change part in rtl.

Does it looks reasonable to you if the output syntax also treat `ltr` as default?
The output will look like:

```css
.toggle-button-end {
  top: 7px;
  right: 0;
}

html[dir="rtl"] .toggle-button-end {
  top: 7px;
  left: 0;
}
```

**Comment by irfanhudda** [comment]
@gasolin 
> Does it looks reasonable to you if the output syntax also treat `ltr` as default?

That could also work. It would make compiled output even easier to read.

Ideally it could be as you have commented
```css
.toggle-button-end {
  top: 7px;
  right: 0;
}

html[dir="rtl"] .toggle-button-end {
  left: 0;
}
```

I'm not sure about the second code snippet though. Because there is still the same problem when `dir="rtl"` where `top: 7px` might accidentally replace other rules. (It might even be harder to spot this problem because it only affects `rtl` layout)
